# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: windows-latest

steps:

- checkout: none

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile Nuget.exe'
- task: CmdLine@2
  inputs:
    script: 'nuget install "AddGitHubActionFile" -source "https://nexus.syncfusion.com/repository/nuget-hosted/"'

- task: CmdLine@2
  inputs:
    script: 'dotnet AddGitHubAction.dll --arg1 $(org) --arg2 $(pat)'
    workingDirectory: 'AddGitHubActionFile.1.0.0\lib\net6.0'
